### ISSUE TITLE
[Bug] Creating data account for program returns error -32602 invalid transaction: index out of bounds

### ISSUE THREAD

**Issue by nukec** [bmresearch/Solnet#190]
**Describe the bug**
When trying to submit transaction simulation when creating new data account for program, I get the follow error:

> {"jsonrpc":"2.0","error":{"code":-32602,"message":"invalid transaction: index out of bounds"},"id":3}

**To Reproduce**
```
Account dataAccount = new();
const long gameAccountSpace = 307; // refactor this into proper layout later
byte[] tx3 = new TransactionBuilder().SetRecentBlockHash(blockHash.Result.Value.Blockhash)
                                                .SetFeePayer(this._account)
                                                .AddInstruction(SystemProgram.CreateAccount(
                                                                    this._account.PublicKey,
                                                                    dataAccount.PublicKey,
                                                                    balanceForRentExemption.Result,
                                                                    gameAccountSpace,
                                                                    programId))
                                                .Build(new List<Account> { this._account });

            RequestResult<ResponseValue<SimulationLogs>>? simulatedTransactionRequest2 = await this._rpcClient.SimulateTransactionAsync(transaction: tx3, commitment: Commitment.Confirmed);
            Debug.Write(simulatedTransactionRequest2);
```

**Expected behavior**
Create data account for program.

**Screenshots**
![image](https://user-images.githubusercontent.com/3589518/130371543-c7dfa3ba-5539-4f05-aebe-b9b8ef55598c.png)

**Comment by murlokito** [comment]
This is not a bug.
When creating an account using `SystemProgram.CreateAccount(account, newAccount...) ` the transaction must be signed by both the `account` and `newAccount`.

In this case, you need to add the `dataAccount` to the list of signers.

**Comment by murlokito** [comment]
Some more context on this, that error message from the RPC means that there is a signature missing for the transaction.

**Comment by nukec** [comment]
That works thanks, how do you know "index out of bounds " means signature is missing in this specific case? Is there any docs or perhaps I would have to look into solana core source code.

**Comment by murlokito** [comment]
I know this because I have been through a lot of these cases. But to be more specific it has to do with the wire format which encodes the transaction, you can see the methods which encode these in the Transaction/MessageBuilder and the ones which decode them in the Transaction and Message models.

In essence the RPC is going to try to decode the transaction and it will succeed because it is properly formatted. Wwhen it attempts to validate the transaction it will go through all of the instructions and see which accounts are marked as being a signing account, this number of signing accounts is specified in the message header, and if the number of signatures present in the transaction is lower than the number of required signers this error will be thrown because it will try to access an index of the signatures array which is out of bounds.

**Comment by nukec** [comment]
That makes sense, I was using 0.3.5 until few hours ago, which was probably adding all accounts as signers in this case by default, so code was working previously.

**Comment by murlokito** [comment]
Yes, upgrading to v0.4 had some breaking changes we introduced in order to have proper SDK interoperability. We were passing Accounts and not public keys before, and the Transaction Builder would take care of everything internally, this is not the case anymore and we really have to pass the appropriate signers into the the Build method.
