### ISSUE TITLE
Initialize a wallet and get it's token balances with private key.

### ISSUE THREAD

**Issue by Tr1Fecta-7** [bmresearch/Solnet#318]
Hi maintainers of solnet, I have a question. How do I initialize a Wallet object without the mnemonic? I'm trying to use the private key that I have exported from Phantom

**Comment by murlokito** [comment]
The `Wallet` primitives are to be used either with a mnemonic or with a private key file generated by the `solana-keygen- CLI tool.

To import an account from Phantom by exporting the private key you will also need the corresponding public key.

Then you can initialize it with:

```csharp
var account = new Account(privateKey, publicKey);
```

And you can use it to sign transactions, submit instructions etc because `Account` implements the `Sign` and  `Verify` methods.

**Comment by murlokito** [comment]
> Thanks for the quick reply. I thought at first the Wallet object was required in order to submit transactions or sign them, but now I see.

It is not necessary, all of the methods that are used to sign a message / craft a transaction receive either a signature in `byte[]` or `string`, depending on the cases, or they need an `Account` which then is used to call `account.Sign()`.

**Comment by murlokito** [comment]
For a better understanding of this, I recommend taking a look at the examples, `HelloWorldExample` is fairly simple as it only submits a transaction with a memo, all others are more complex and the Multi signature examples are the most complex (and confusing because in the examples we actually have access to all of the signatures and it is not that simple.)

**Comment by Tr1Fecta-7** [comment]
Thanks, I'll look into it. Another question, my winforms application seems to freeze when running this piece of code:

`
Account account = new Account("XXXXX", "XXXX");
MessageBox.Show($"Publicc key: {account.PublicKey}");

var rpcClient = ClientFactory.GetClient(Cluster.MainNet);
var tokens = TokenMintResolver.Load();

TokenWallet tokenWallet = TokenWallet.Load(rpcClient, tokens, account);

 foreach (var account1 in tokenWallet.TokenAccounts().WithNonZero())
{
     MessageBox.Show($"{account1.TokenName} - Amount: {account1.QuantityDecimal} - Public Key: {account1.PublicKey}");
}
`

It seems to get stuck on the line `TokenWallet tokenWallet = TokenWallet.Load(rpcClient, tokens, account);`

**Comment by murlokito** [comment]
That's probably due to I/O, same thing happens in Avalonia applications. You should use the `LoadAsync()` method.

**Comment by Tr1Fecta-7** [comment]
Thank you! That worked!

**Comment by tiago18c** [comment]
I guess we can close this?

ps: in the future, open a discussion instead!

Or come to our [discord](https://discord.gg/cReXaBReZt)!
