### ISSUE TITLE
Create Associated Token Account example

### ISSUE THREAD

**Issue by GabrielePicco** [bmresearch/Solnet#349]
I think the example in [AssociatedTokenAccountsExample](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Examples/AssociatedTokenAccountsExample.cs) is not updated. 

The definition of [CreateAssociatedTokenAccount](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Programs/AssociatedTokenAccountProgram.cs#L41) has a different signature and perform the DeriveAssociatedTokenAccount internally, while the DeriveAssociatedTokenAccount in the example is done externally.

**Comment by murlokito** [comment]
The method `DeriveAssociatedTokenAccount` is used merely to deterministically derive the `PublicKey` of the token account for the given owner and token mint `PublicKey`s, while the method `CreateAssociatedTokenAccount` is used to craft the `TransactionInstruction` which can be submitted to the network in order to actually create the account with the address that `DeriveAssociatedTokenAccount` computes.

In the example, the derived address is necessary to perform a [token transfer](https://github.com/bmresearch/Solnet/blob/master/src/Solnet.Examples/AssociatedTokenAccountsExample.cs#L114), which is why it is done externally so that it can then be passed into another instruction.

Does this answer your question?

**Comment by GabrielePicco** [comment]
Thank you @murlokito, yes it does, but the call to CreateAssociatedTokenAccount will not internally derive another address from the externally created address and the owner? Is this expected?

**Comment by GabrielePicco** [comment]
Thank you @murlokito, yes it does answer my question. Closing the issue.
