### ISSUE TITLE
Please support xamarin

### ISSUE THREAD

**Issue by liuzhenLz** [bmresearch/Solnet#382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by murlokito** [comment]
Unknown if this issue is related to #383. We have successfully used multiple frameworks with the library (Avalonia, MAUI, Uno), so I'm wondering what makes it incompatible with Xamarin?

If this is somehow related to .Net Standard 2 you can [see here](https://github.com/garbles-dev/Solana.Unity) for a backport that is .Net Standard 2 compatible.
