### ISSUE TITLE
[Bug] null url?

### ISSUE THREAD

**Issue by zxcvqwerasdf** [bmresearch/Solnet#466]
https://github.com/bmresearch/Solnet/blob/bcb31444c3700264a8e7adb701a2df3d9d7cec1c/src/Solnet.Rpc/Core/Http/JsonRpcClient.cs#L89
and
https://github.com/bmresearch/Solnet/blob/bcb31444c3700264a8e7adb701a2df3d9d7cec1c/src/Solnet.Rpc/Core/Http/JsonRpcClient.cs#L199

**Comment by zxcvqwerasdf** [comment]
Replace (string)null to NodeAddress

**Comment by BifrostTitan** [comment]
The class is protected and by default its null because it uses the read-only BaseAddress used during initialization. Allowing on-the-fly RPC endpoint swapping can lead to a MITM exploit when another process tries to inject code or manipulate the memory of the dynamic link library. It is null for security purposes. If you wish to have more options for RPC endpoints I recommend using a child class that allows hot swapping the endpoints.
